version: '2'

services:
  hackathon:
    build: .
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '8000:5000'

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hackathon_admin
      MYSQL_PASSWORD: hackathon_2021
      MYSQL_DATABASE: hackathon_database

